### PR TITLE
Now Works With Rider

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
I look at the extension instead of the metadata now.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thanks for taking the time to find this!
I really want to use the metadata though because in my projects the templates may have various different extensions (it's not only used for html) and I also don't want to accidentally compile something the user didn't want to. Do you know if there's an issue on YouTrack related to the bug that prevents Rider from picking up those metadata properties?

**Comment by khalidabuhakmeh** [comment]
No worries, I didn't expect you to merge it.

This issue currently is a good spot. https://youtrack.jetbrains.com/issue/RIDER-30839

**Comment by Tyrrrz** [comment]
Performed my civic duty and upvoted it.

**Comment by Tyrrrz** [comment]
Duplicate of #5

**Pull request closed without merging**
