### PR TITLE
Separate into multiple packages

### PR DESCRIPTION
**Pull request by KevinGliewe**
**Warning!** This PR breaks compatibility to version `2.0.3`.

This PR fixes https://github.com/Tyrrrz/MiniRazor/issues/6 by moving `ITemplate`, `TemplateBase` and `RawString` into its own package. 
This way a project using the code generator `MiniRazor.CodeGen` does avoid inheriting all the dependencies of `MiniRazor`.

I also bumped the version to `2.0.4` to avoid conflicts, but a bump in the minor version may be more appropriate since it breaks the compatibility to version `2.0.3`.

The CD now deploys `MiniRazor` **AND** `MiniRazor.Shared`. So a nuget token with a wildcard (`MiniRazor*` i think) woud be needed. Otherwise two separate tokens should also work (But needs a modification of the CD workflow).

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thanks!
Do I understand correctly that `MiniRazor.Shared` now contains types related runtime compilation as well? Maybe it would be better to rename that to `MiniRazor` and instead rename the other one (that contains the source generator) to `MiniRazor.CodeGen`?

**Comment by KevinGliewe** [comment]
My thought process of naming it ‘Shared’ is to signalize the potential consumer that this package only contains the minimal shared dependencies needed to interface with the [source generator](https://github.com/Tyrrrz/MiniRazor/tree/master/MiniRazor.CodeGen). A bit like Microsoft’s `*.Abstractions` libraries.

Imho keeping the name for `MiniRazor` would makes sense, because it still contains the 'meat' of this project (Also: [`MiniRazor.CodeGen`](https://github.com/Tyrrrz/MiniRazor/tree/master/MiniRazor.CodeGen) is already taken 😉).
It would be strange making `MiniRazor.Shared` the 'main' project, since it only contains `ITemplate`, `TemplateBase` and `RawString`.

**Comment by KevinGliewe** [comment]
Sorry, i didn't address your actual question:
> Do I understand correctly that `MiniRazor.Shared` now contains types related runtime compilation as well?
Yes, `ITemplate` and `TemplateBase` are needed for the runtime compilation.

**Comment by Tyrrrz** [comment]
Wouldn't it be possible to have the following structure:

- `MiniRazor` contains shared types and everything needed for runtime compilation. Depends on `Microsoft.AspNetCore.Razor.Language`
- `MiniRazor.CodeGen` depends on `MiniRazor` (via the usual [hacky way](https://github.com/Tyrrrz/MiniRazor/blob/4cefe20dc13d7a0302b6c43accaae0241b24c001/MiniRazor.CodeGen/MiniRazor.CodeGen.csproj#L13-L28) since it's source generators + `PrivateAssets="all"`) and adds codegen capabilities

**Comment by KevinGliewe** [comment]
I am not sure if i understand this correctly. What do you mean with the core part?
What i consider the core part would be the class `MiniRazor.Razor` and its dependencys sice it represents the core functionality of this project.

By making the core part private you meant using `PrivateAssets="all"` I assume?

The core problem we are facing here is the dependencies for the runtime generation vs compile time generation:

 - For the runtime generation we need to use `MiniRazor.Razor` and therefore the dependency to `Microsoft.AspNetCore.Razor.Language` is unavoidable.

- For the compile time generation the only reference we need at runtime is the `TemplateBase`, since it needs to be inherited by the templates, and its dependencies (Which is `ITemplate` and `RawString`). The dependency to `MiniRazor.Razor` exists only during compilation because of `MiniRazor.CodeGen`.

To get the least number of dependencies for the compile time generation, we need to have a separate package with only `ITemplate`, `TemplateBase` and `RawString`. This is the reason I separated them into `MiniRazor.Shared`.

If you compile `MiniRazor.CodeGen.Demo` from my PR you will see the only runtime dependency is `MiniRazor.Shared`, no `Microsoft.AspNetCore.Razor.Language` or anyting else.

## So a short recap:

### The dependencies for:
 - Runtime generation:
   * During runtime:
     - `class MiniRazor.Razor`
     - `class TemplateBase`
   * During compile time:
     - None
 - Compile time generation:
   * During runtime:
     - `class TemplateBase`
   * During compile time:
     - `class TemplateClassGenerator`
     - `class MiniRazor.Razor`

### So we need 3 projects to separate the accessability correctly:
 - `class MiniRazor.Razor` -> project `MiniRazor`
 - `class TemplateBase` -> project `MiniRazor.Shared`
 - `class TemplateClassGenerator` ->project `MiniRazor.CodeGen`
   
Sorry for the long winded answer! 😅

**Comment by Tyrrrz** [comment]
Ah I see! Thanks for the explanation. So we need the shared project because the classes created by codegen depend on `TemplateBase` at runtime, so it cannot be marked as private, correct?

I wonder, maybe it's possible to somehow emit `TemplateBase` from the source generator to embed it within the user's project? I'm falling asleep, so it might be a stupid idea though. 🙂 

Ideally I want to keep the number of packages to a minimum, that's why I'm trying to find ways to get rid of `MiniRazor.Shared` 😅

**Comment by KevinGliewe** [comment]
> Ah I see! Thanks for the explanation. So we need the shared project because the classes created by codegen depend on `TemplateBase` at runtime, so it cannot be marked as private, correct?

Exactly 👍

> I wonder, maybe it's possible to somehow emit `TemplateBase` from the source generator to embed it within the user's project? I'm falling asleep, so it might be a stupid idea though. 🙂

This would only work for a single project, but when you split your views over multiple projects then you will run into issues. We could put the indivisual `TemplateBase`s inside a project specific namespace to avoid type collisions but these `TemplateBase`s wouldn’t be castable into each other ; At least not without a workaround: Using the partial class definition, it would be possible to add a inheritance from a shared interface to the razor template.

> Ideally I want to keep the number of packages to a minimum, that's why I'm trying to find ways to get rid of `MiniRazor.Shared` 😅

I can't blame you! 😄👍 But in the end it comes down to a compromise…

**Comment by KevinGliewe** [comment]
So, i implemented your proposal. 

This implementation emits `ITemplate`, `TemplateBase` and `RawString` into the user’s project, so there is no need to reference `MiniRazor`. This works well in `MiniRazor.CodeGen.Demo`, because it references `MiniRazor.CodeGen` directly. But I can’t get rid of `Microsoft.AspNetCore.Razor.Language` when using the `MiniRazor` nuget package. 

I added the `MiniRazor.CodeGen.DemoPkg` project to test the behavior when consuming the nuget package. 

Do you have any idea how to get rid of `Microsoft.AspNetCore.Razor.Language` for this usecase? `PrivateAssets="all"` doesn't do the trick...

If you want to test it yourself, check this [branch](https://github.com/KevinGliewe/MiniRazor/tree/srcgen) out.

Before using `Microsoft.AspNetCore.Razor.Language`, you have to run ` dotnet pack --configuration Release`

**Comment by Tyrrrz** [comment]
Thanks for trying out my insane idea 😅 
It actually looks pretty nice! However, now I start to realize how difficult it will be to reason about code with this approach, especially since `TemplateBase` and others will be shared across multiple projects. It reminded me why I didn't like the file linking approach I used originally, because it was really hard to determine what dependencies the file has.

So I'm finally coming to terms with this structure:

- Shared: `TemplateBase`, `ITemplate`, `RawString`
- Runtime compilation: `Razor`, `TemplateDescriptor`, `Microsoft.AspNetCore.Razor.Language`
- Buildtime compilation: Shared (explicit dependency) + Runtime compilation (private dependency)

One thing that bugs me a bit is the naming and the fact `TemplateBase` is placed inside `MiniRazor.Shared.` namespace. So maybe do this:

- Shared package name: `MiniRazor.Runtime` (as in, library needed at runtime, not to be confused with runtime compilation 😂), Root namespace: `MiniRazor` (so that `TemplateBase` ends up in `MiniRazor.TemplateBase`)
- Runtime compilation package name: `MiniRazor.Compiler` (because it's just a wrapper around the compiiler/transpiler), Root namespace: `MiniRazor.Compiler`
- Buildtime compilation package name: `MiniRazor.CodeGen`

And finally, we can add a meta package called `MiniRazor` that would combine both `MiniRazor.Compiler` and `MiniRazor.CodeGen` together, so it would function in the same way (albeit the namespaces will be different, but it's fine). I'm not actually sure how to create meta packages these days, is it possible to make a `.csproj` without any source files and only package references?

This will result in 4 packages in total 😱 But since we're deploying them all at the same time, it shouldn't really matter, I hope. Will probably need some `Directory.Build.props` file to share metadata between them.

What do you think about this? Sorry for setting you on this wild goose chase. 😅

**Comment by KevinGliewe** [comment]
> Thanks for trying out my insane idea 😅

Hey, it was a great idea and i was eager to try it out... 😄

> It actually looks pretty nice! However, now I start to realize how difficult it will be to reason about code with this approach, especially since `TemplateBase` and others will be shared across multiple projects. It reminded me why I didn't like the file linking approach I used originally, because it was really hard to determine what dependencies the file has.

Yea, even IntelliSense has it's problems with this approach.

> And finally, we can add a meta package called `MiniRazor` that would combine both `MiniRazor.Compiler` and `MiniRazor.CodeGen` together, so it would function in the same way it does now (albeit the namespaces will be different, but it's fine). I'm not actually sure how to create meta packages these days, is it possible to make a `.csproj` without any source files and only package references?

I don't think putting `MiniRazor.Compiler` and `MiniRazor.CodeGen` into the same package would work. Since `MiniRazor.Compiler` has to be a public asset. Referencing this package in a project with compile time generation, would include int’s dependencies as well (`Microsoft.AspNetCore.Razor.Language `). And you would have to reference it to get the `MiniRazor.CodeGen` functionality.

A possible alternative could be: Putting `MiniRazor.Runtime` and `MiniRazor.CodeGen` with a reference to the `MiniRazor.Compiler` as `PrivateAssets="all" ` into the same package. This way you only have to reference this one package for compile time generation, which has only `MiniRazor.Runtime` publicly exposed.
This should hopefully stop the “dependency spilling”.

What’s your opinion on this?

> What do you think about this? Sorry for setting you on this wild goose chase. 😅

Don’t be sorry! I was the one who started it... Thank you for sticking with me. 😉

**Comment by KevinGliewe** [comment]
I updated my PR to reflect the new structure.

The new package structure is now as follows:

 - package `MiniRazor`
   * public `TemplateBase`
   * private `MiniRazor.CodeGen`
   * private `Microsoft.AspNetCore.Razor.Language`
 - package `MiniRazor.Compiler`
   * public `Razor`
   * public `Microsoft.AspNetCore.Razor.Language`

In addition I did some changes:
 - The namespace reconstruction is improved by analyzing the directory structure and add it to the RootNamespace of the project.
 - Version bumped to `2.1.0`
 - Updated `Readme.md` to reflect the new structure
 - Movd all shared package informations into `Directory.Build.props`
 - Export the version definition into `Version.props`

**Comment by Tyrrrz** [comment]
> I don't think putting `MiniRazor.Compiler` and `MiniRazor.CodeGen` into the same package would work. Since `MiniRazor.Compiler` has to be a public asset. Referencing this package in a project with _compile time generation_, would include int’s dependencies as well (`Microsoft.AspNetCore.Razor.Language `). And you would have to reference it to get the `MiniRazor.CodeGen` functionality.

Yeah, that's fine, because they would still be able to reference `MiniRazor.CodeGen` instead if they want to. What I mean by metapackage is that `MiniRazor` will have an explicit package dependency on `MiniRazor.Compiler` and `MiniRazor.CodeGen`, but `MiniRazor` will itself contain no code. This means that the user's project will include  `MiniRazor.Compiler` and `MiniRazor.CodeGen` by the way of transitive dependencies, which is enough to use them.

Basically, if the user chooses to reference `MiniRazor` package, they will gain access to both compile-time generation and runtime compilation, but they will incur the `Microsoft.AspNetCore.Razor.Language` dependency regardless of what they're doing. This is effectively how it works right now.

If the user wants to optimize their process, they will instead include either `MiniRazor.Compiler` or `MiniRazor.CodeGen` instead of `MiniRazor`. This way we offer two options: easy setup where everything is one package and you don't have to choose (this will actually satisfy a lot of people) and fine-tuned setup where you can optimize your dependencies.

I like this approach because it allows us to essentially make this a non-breaking change (if we adjust namespaces to how they were before) and also makes better use of high-level `MiniRazor` package.

> I don't think putting `MiniRazor.Compiler` and `MiniRazor.CodeGen` into the same package would work. Since `MiniRazor.Compiler` has to be a public asset. Referencing this package in a project with _compile time generation_, would include int’s dependencies as well (`Microsoft.AspNetCore.Razor.Language`). And you would have to reference it to get the `MiniRazor.CodeGen` functionality.

To clarify again, I didn't mean put them into the same package, but adding them as a reference to a high level metapackage. Kinda like ASP.NET Core used to work where all packages were aggregated under one metapackage: https://www.nuget.org/packages/Microsoft.AspNetCore.App/ (click dependencies)

**Comment by Tyrrrz** [comment]
So just to clarify again, this is what I had in mind:

User references `MiniRazor.CodeGen` because they only want build-time compilation:
- **Private** dependency on `MiniRazor.CodeGen` (this library will be used during build but will not be included with the user's binaries)
- **Transitive** dependency on `MiniRazor.Runtime` (this library will be included with the user's binaries)
- **Embedded** dependency on `MiniRazor.Compiler` (this library will be embedded inside the codegen package)
- **Embedded** dependency on `Microsoft.AspNetCore.Razor.Language` (this library will be embedded inside the codegen package)

User references `MiniRazor.Compiler` because they only want runtime compilation:
- **Direct** dependency on `MiniRazor.Compiler` (this library will be included with the user's binaries)
- **Transitive** dependency on `MiniRazor.Runtime` (this library will be included with the user's binaries)
- **Transitive** dependency on `Microsoft.AspNetCore.Razor.Language` (this library will be included with the user's binaries)

User references `MiniRazor` because they're not sure what they want or just want both workflows:
- **No** dependency on `MiniRazor` (this package contains no code, it's only a metapackage)
- **Transitive** dependency on `MiniRazor.Compiler` (this library will be included with the user's binaries)
- **Transitive** dependency on `MiniRazor.Runtime` (this library will be included with the user's binaries)
- **Transitive** dependency on `Microsoft.AspNetCore.Razor.Language` (this library will be included with the user's binaries)
- **Embedded** dependency on `MiniRazor.Compiler` (this library will be embedded inside the codegen package)
- **Embedded** dependency on `Microsoft.AspNetCore.Razor.Language` (this library will be embedded inside the codegen package)

So the last approach is clearly suboptimal because it has more dependencies and actually duplicates some dependencies as well, but it can be offered as an easy "no brainer" option to simplify things.

**Comment by Tyrrrz** [comment]
PS: also don't worry about changing readme or the changelog. I will most likely have to do a pass over after everything is merged anyway.

**Comment by KevinGliewe** [comment]
Oh... I see. Thanks for the detailed explanation.

So what I would do now is following:
 - Rename the Project `MiniRazor` to `MiniRazor.Runtime`.
 - Revert the namespace changes, to get the backward combability.
 - Add a meta package called `MiniRazor` with dependencies to `MiniRazor.Runtime` and `MiniRazor.Compiler`.

I don't have much experience with meta packages, but I think this should work for us?

``` xml
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>MiniRazor</id>
    <version>2.1.0</version>
    <authors>Tyrrrz</authors>
    <owners>Tyrrrz</owners>
    <licenseUrl>https://raw.githubusercontent.com/Tyrrrz/MiniRazor/master/License.txt</licenseUrl>
    <projectUrl>https://github.com/Tyrrrz/MiniRazor/</projectUrl>
    <icon>images\favicon.png</icon>
    <description>Portable Razor compiler and code generator</description>
    <copyright>Copyright (C) Alexey Golub</copyright>
    <tags>razor template engine cshtml codegen code generation source generators</tags>
    <repository type="git" url="https://github.com/Tyrrrz/MiniRazor"/>
    <dependencies>
      <group>
        <dependency id="MiniRazor.Runtime" version="2.1.0" include="All" />
        <dependency id="MiniRazor.Compiler" version="2.1.0" include="All" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="..\favicon.png" target="images\" />
    <file src="..\MiniRazor.props" target="build\" />
  </files>
</package>
```

**Comment by KevinGliewe** [comment]
I created a [branch](https://github.com/KevinGliewe/MiniRazor/tree/metapack-clean) with the meta-package and a clean commit history.

It preserves the backward compatibility when referencing the `MiniRazor` [meta-package](https://github.com/KevinGliewe/MiniRazor/blob/metapack-clean/MiniRazor.nuspec), while giving the option to reference `MiniRazor.Runtime` directly to get rid of `Microsoft.AspNetCore.Razor.Language`.

What do you think? Is this how you had it in mind?

**Comment by Tyrrrz** [comment]
> What do you think? Is this how you had it in mind?

Yes! Except I would prefer if we could make a nuget package without using .nuspec but .csproj instead. I googled around and I think this is achievable if you create a .csproj and include the following properties:

```xml
<IncludeBuildOutput>false</IncludeBuildOutput>
<IncludeSymbols>false</IncludeSymbols>
```

This makes it so the project doesn't produce any build output and effectively becomes a metapackage. By using csproj instead of nuspec it will work x-platform (nuspec is only Windows I think) and would also benefit from `Directory.Build.Props`.

**Comment by KevinGliewe** [comment]
Nice, i google for something like this as well but couldn’t find anything. I updated the [branch](https://github.com/KevinGliewe/MiniRazor/tree/metapack-clean) to use a .csproj for the meta package and it works perfectly.

**Comment by Tyrrrz** [comment]
Awesome! I think this is the way to go. Can we get it in?
I don't know if you can swap branches in this PR, but if not: you can overwrite your `master` branch with `metapack-clean` like this:

```
git checkout master
git reset --hard 4cefe20
git merge metapack-clean
git push --force-with-lease
```

**Comment by KevinGliewe** [comment]
It seems to have worked. I force pushed the reset and merged master branch and the PR has been updated to the new commits.

Ready to be merged! 👍

**Comment by Tyrrrz** [comment]
Thanks! I will hopefully clean it up and release this coming week.

**Pull request merged**
